base_frame: base_footprint
odom_frame: odom
map_frame:  map

throttle_scans : 1
map_update_interval: 1.0
resolution: 0.025
delta: 0.01
transform_publish_period: 0.05

use_scan_matching: true
use_scan_barycenter: true
minimum_travel_distance: 0.1 
minimum_travel_heading: 0.08
scan_buffer_size: 70
scan_buffer_maximum_scan_distance: 10.0

link_match_minimum_response_fine: 0.12
link_scan_maximum_distance: 5.0
loop_search_maximum_distance: 3.0
do_loop_closing: true
loop_match_minimum_chain_size: 10
loop_match_maximum_variance_coarse: 0.4
loop_match_minimum_response_coarse: 0.8
loop_match_minimum_response_fine: 0.8

correlation_search_space_dimension: 0.3
correlation_search_space_resolution: 0.01
correlation_search_space_smear_deviation: 0.03

loop_search_space_dimension: 8.0
loop_search_space_resolution: 0.01
loop_search_space_smear_deviation: 0.03

distance_variance_penalty: 0.3
angle_variance_penalty: 0.349
fine_search_angle_offset: 0.00349
coarse_search_angle_offset: 0.349
coarse_angle_resolution: 0.0349
minimum_angle_penalty: 0.9
minimum_distance_penalty: 0.5
use_response_expansion: false